var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

//首页第一次上拉加载更多的数据
router.get('/api/index_list/1/data/2',function(req,res,next){
	return res.json({
		code:"0",
		data:[
			{
				type:"commondityList",
				data:[
					{
						id:1,
						imgUrl:"../../static/img/commodity1.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"48.00",
						oprice:"99.00",
						discount:"5.8"
					},
					{
						id:2,
						imgUrl:"../../static/img/commodity2.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					{
						id:3,
						imgUrl:"../../static/img/commodity3.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					{
						id:4,
						imgUrl:"../../static/img/commodity4.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					}
				]
			},
		]
	});
});	
//运动户外第一次上拉加载更多的数据
router.get('/api/index_list/2/data/2',function(req,res,next){
	return res.json({
		code:"0",
		data:[
			{
				type:"commondityList",
				data:[
					{
						id:1,
						imgUrl:"../../static/img/commodity1.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"48.00",
						oprice:"99.00",
						discount:"5.8"
					},
					{
						id:2,
						imgUrl:"../../static/img/commodity2.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					{
						id:3,
						imgUrl:"../../static/img/commodity3.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					{
						id:4,
						imgUrl:"../../static/img/commodity4.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					}
				]
			},
		]
	});	
});
//运动户外第一次加载的数据
router.get('/api/index_list/2/data/1',function(req,res,next){
	return res.json({
		code:"0",
		data:[
			{
				type:"bannerList",
				imgUrl:"../../static/img/banner1.jpg",
			},
			{
				type:"iconList",
                data:[
					{
						imgUrl:"../../static/img/icons1.png",
						name:"sports"
					},
					{
						imgUrl:"../../static/img/icons2.png",
						name:"sports"
					},
					{
						imgUrl:"../../static/img/icons3.png",
						name:"sports"
					},
					{
						imgUrl:"../../static/img/icons4.png",
						name:"ssports"
					},
					{
						imgUrl:"../../static/img/icons5.png",
						name:"sports"
					},
					{
						imgUrl:"../../static/img/icons6.png",
						name:"sports"
					},
					{
						imgUrl:"../../static/img/icons7.png",
						name:"sports"
					},
					{
						imgUrl:"../../static/img/icons8.png",
						name:"sports"
					}

				]
			},
			{
				type:"hotList",
				data:[
					{
						id:1,
						imgUrl:"../../static/img/hot1.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"48.00",
						oprice:"99.00",
						discount:"5.8"
					},
					{
						id:2,
						imgUrl:"../../static/img/hot2.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					{
						id:3,
						imgUrl:"../../static/img/hot3.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					]
			},
			{
				type:"shopList",
				data:[{
					bigUrl:"../../static/img/shop.jpg",
					data:[
						
							{
								id:1,
								imgUrl:"../../static/img/shop1.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							},
							{
								id:2,
								imgUrl:"../../static/img/shop2.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							},
							{
								id:3,
								imgUrl:"../../static/img/shop3.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							},
							{
								id:4,
								imgUrl:"../../static/img/shop1.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							}
						
					]
				}]
			},
				{
					type:"commondityList",
					data:[
						{
							id:1,
							imgUrl:"../../static/img/commodity1.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"48.00",
							oprice:"99.00",
							discount:"5.8"
						},
						{
							id:2,
							imgUrl:"../../static/img/commodity2.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						},
						{
							id:3,
							imgUrl:"../../static/img/commodity3.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						},
						{
							id:4,
							imgUrl:"../../static/img/commodity4.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						}
					]
				},
		]
	});
});
//服饰内衣第一次加载的数据
router.get('/api/index_list/3/data/1',function(req,res,next){
	return res.json({
		code:"0",
		data:[
			{
				type:"bannerList",
				imgUrl:"../../static/img/banner1.jpg",
			},
			{
				type:"iconList",
                data:[
					{
						imgUrl:"../../static/img/icons1.png",
						name:"clothes"
					},
					{
						imgUrl:"../../static/img/icons2.png",
						name:"clothe"
					},
					{
						imgUrl:"../../static/img/icons3.png",
						name:"clothe"
					},
					{
						imgUrl:"../../static/img/icons4.png",
						name:"clothe"
					},
					{
						imgUrl:"../../static/img/icons5.png",
						name:"clothe"
					},
					{
						imgUrl:"../../static/img/icons6.png",
						name:"csports"
					},
					{
						imgUrl:"../../static/img/icons7.png",
						name:"food"
					},

				]
			},
			{
				type:"hotList",
				data:[
					{
						id:1,
						imgUrl:"../../static/img/hot1.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"48.00",
						oprice:"99.00",
						discount:"5.8"
					},
					{
						id:2,
						imgUrl:"../../static/img/hot2.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					{
						id:3,
						imgUrl:"../../static/img/hot3.jpg",
						name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
						cprice:"148.00",
						oprice:"399.00",
						discount:"4.8"
					},
					]
			},
			{
				type:"shopList",
				data:[{
					bigUrl:"../../static/img/shop.jpg",
					data:[
						
							{
								id:1,
								imgUrl:"../../static/img/shop1.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							},
							{
								id:2,
								imgUrl:"../../static/img/shop2.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							},
							{
								id:3,
								imgUrl:"../../static/img/shop3.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							},
							{
								id:4,
								imgUrl:"../../static/img/shop1.jpg",
								name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
								cprice:"48.00",
								oprice:"99.00",
								discount:"5.8"
							}
						
					]
				}]
			},
				{
					type:"commondityList",
					data:[
						{
							id:1,
							imgUrl:"../../static/img/commodity1.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"48.00",
							oprice:"99.00",
							discount:"5.8"
						},
						{
							id:2,
							imgUrl:"../../static/img/commodity2.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						},
						{
							id:3,
							imgUrl:"../../static/img/commodity3.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						},
						{
							id:4,
							imgUrl:"../../static/img/commodity4.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						}
					]
				},
		]
	});
});



//首页第一次加载的数据
router.get('/api/index_list/data', function(req, res, next) {
	//return res.writeHead(200, { "Content-Type":"text/html" , "Access-Control-Allow-Origin":"*"});
	return res.send({
		
		"code":0,
		"data":{
			topBar:[
				{id:1,name:'推荐'},
				{id:2,name:'运动户外'},
				{id:3,name:'服饰内衣'},
				{id:4,name:'鞋靴箱包'},
				{id:5,name:'美妆个护'},
				{id:6,name:'家居数码'},
				{id:7,name:'食品母婴'}
			],
			data:[
				{
				type:"swiperList",
				data:[
					{imgUrl:'../../static/img/swiper1.jpg'},
					{imgUrl:'../../static/img/swiper2.jpg'},
					{imgUrl:'../../static/img/swiper3.jpg'},
				]
			    },
				{
				type:"recommendList",
				data:[
					{
						bigUrl:'../../static/img/Children.jpg',
						data:[
							{imgUrl:'../../static/img/Children1.jpg'},
							{imgUrl:'../../static/img/Children2.jpg'},
							{imgUrl:'../../static/img/Children3.jpg'},
						]
					},
					{
						bigUrl:'../../static/img/Furnishing.jpg',
						data:[
							{imgUrl:'../../static/img/Furnishing1.jpg'},
							{imgUrl:'../../static/img/Furnishing2.jpg'},
							{imgUrl:'../../static/img/Furnishing3.jpg'},
						]
					},
				]
				},
				{
					type:"commondityList",
					data:[
						{
							id:1,
							imgUrl:"../../static/img/commodity1.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"48.00",
							oprice:"99.00",
							discount:"5.8"
						},
						{
							id:2,
							imgUrl:"../../static/img/commodity2.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						},
						{
							id:3,
							imgUrl:"../../static/img/commodity3.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						},
						{
							id:4,
							imgUrl:"../../static/img/commodity4.jpg",
							name:"【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1【经典款】Timberland添柏岚保暖冲锋衣三合一女装潮牌|A1GF1",
							cprice:"148.00",
							oprice:"399.00",
							discount:"4.8"
						}
					]
				}

			],
		}
	});
	//res.end();

});

module.exports = router;
